name: galsen_medic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  http: ^1.3.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/Vector.png
    - assets/icons/star.png
    - assets/images/issa.jpeg
    - assets/images/avatar_placeholder.png
    - assets/images/google.png

flutter_launcher_icons:
  image_path: "assets/images/Vector.png"
  android: true
  ios: true
